# Generated by Django 4.1.4 on 2022-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bookId',
            field=models.PositiveIntegerField(default=1, verbose_name='book id'),
            preserve_default=False,
        ),
    ]
