# Generated by Django 4.1.4 on 2022-12-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_comment_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.book', verbose_name='book id'),
        ),
    ]
