# Generated by Django 4.1.4 on 2022-12-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_rename_book_rating_bookid_alter_comment_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre',
            new_name='genres',
        ),
    ]
