# Generated by Django 4.1.4 on 2022-12-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_genre_book_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genres',
            new_name='genre',
        ),
    ]
