# Generated by Django 4.1.4 on 2022-12-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_genres_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(related_name='genres', to='product.genre'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bookId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.book', verbose_name='book id'),
        ),
    ]
