# Generated by Django 4.1.4 on 2022-12-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_rating_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cover'),
        ),
    ]
