# Generated by Django 4.1.4 on 2022-12-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_rating_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
