# Generated by Django 4.1.4 on 2022-12-27 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_delete_article_delete_reporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='product.book'),
        ),
    ]
