# Generated by Django 4.1.4 on 2022-12-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_rating_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.PositiveIntegerField(verbose_name='Rating'),
        ),
    ]
