# Generated by Django 4.1.4 on 2022-12-27 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_rating_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='average_rate',
            new_name='averageRate',
        ),
    ]
