# Generated by Django 4.1.4 on 2023-01-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rating'),
        ),
    ]
