# Generated by Django 4.1.4 on 2023-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_rating_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.PositiveIntegerField(default=2, verbose_name='Rating'),
            preserve_default=False,
        ),
    ]
