# Generated by Django 4.1.4 on 2023-01-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_rating_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_in_favorite',
            new_name='isInFavorite',
        ),
    ]
