# Generated by Django 4.1.4 on 2023-01-11 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_alter_rating_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='bookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='product.book'),
        ),
    ]
