# Generated by Django 4.1.4 on 2023-01-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_alter_rating_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.PositiveIntegerField(verbose_name='name'),
        ),
    ]
