# Generated by Django 4.1.4 on 2023-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_alter_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isInFavorite',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
