# Generated by Django 4.1.4 on 2023-01-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_book_isinfavorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
    ]
