# Generated by Django 4.1.4 on 2022-12-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_book_cover'),
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(to='product.book'),
        ),
    ]
