# Generated by Django 4.1.4 on 2022-12-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_book_cover'),
        ('user', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='product.book'),
        ),
    ]
