# Generated by Django 4.1.4 on 2022-12-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_comments_remove_user_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorites',
            new_name='bookId',
        ),
    ]
