# Generated by Django 4.1.4 on 2022-12-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='Your name'),
            preserve_default=False,
        ),
    ]
