# Generated by Django 4.1.4 on 2023-01-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Your avatar'),
        ),
    ]
