# Generated by Django 4.1.4 on 2023-01-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bookId',
            new_name='favorites',
        ),
    ]
