# Generated by Django 4.1.4 on 2023-01-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_remove_rating_name_rating_rating'),
        ('user', '0018_rename_bookid_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='user', to='product.book'),
        ),
    ]
