# Generated by Django 4.1.4 on 2023-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='', verbose_name='Your avatar'),
        ),
    ]
